"""
JSON-Lines to Excel conversion module.

This module provides functionality to convert JSON-Lines files generated by the
GenAI classifier into nicely formatted Excel workbooks.
"""

import json
import pathlib
from collections import defaultdict
from typing import List, Dict, Any

import pandas as pd
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


def load_jsonl(file_path: pathlib.Path) -> List[Dict[str, Any]]:
    """Read a JSON‑Lines file and return a list of Python dictionaries."""
    records = []
    with file_path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on line {line_no}: {exc}") from exc
    return records


def flatten_record(record: Dict[str, Any]) -> Dict[str, Any]:
    """
    Turn a single JSON record into a flat dict suitable for a pandas DataFrame.

    For each feature we create columns:
        <name>                     – raw feature name (debugging aid)
        <name>-class               – feature class if present
        <name>-confidence
        <name>-matched_tags        – tags joined by "; "
        <name>-exists
        <name>-reason
    """
    flat: Dict[str, Any] = {"text": record.get("text", "")}
    for feat in record.get("features", []):
        name = feat.get("name")
        resp = feat.get("response", {})
        feat_class = resp.get("class")  # Get the class field if it exists

        flat[name] = name
        # Add class column if the feature has a class
        if feat_class is not None:
            flat[f"{name}-class"] = feat_class
        flat[f"{name}-confidence"] = resp.get("confidence")
        tags = resp.get("matched_tags", [])

        if len(tags):
            flat[f"{name}-matched_tags"] = "; ".join(tags) if tags else ""

        flat[f"{name}-exists"] = resp.get("exists")
        flat[f"{name}-reason"] = resp.get("reason", "")
    return flat


def group_by_field(records: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    """Group the flattened rows by their original ``field`` value."""
    grouped: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for rec in records:
        field_val = rec.get("field", "unknown")
        grouped[field_val].append(flatten_record(rec))
    return grouped


def apply_pretty_formatting(ws):
    """
    Apply visual tweaks to a worksheet:

    * column ``text`` ≈ 15 cm wide (≈ 55 character units)
    * wrap text for every cell
    * header: bold, centred, light‑blue fill
    * zebra striping – every second data row gets a light‑gray fill
    * conditional colour:
          1 / PRAWDA → light‑green
          0 / FAŁSZ  → light‑blue
    """
    # ----- 1️⃣ column width for ``text`` (≈15 cm) -----
    for col in ws.iter_cols(min_row=1, max_row=1):
        for cell in col:
            if cell.value == "text":
                col_letter = get_column_letter(cell.column)
                ws.column_dimensions[col_letter].width = 55  # ≈15 cm
                break

    # ----- reusable styles -----
    wrap_align = Alignment(wrap_text=True, vertical="top")
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(fill_type="solid", start_color="4F81BD")  # light‑blue
    zebra_fill = PatternFill(fill_type="solid", start_color="D3D3D3")  # light‑gray
    green_fill = PatternFill(fill_type="solid", start_color="C6EFCE")  # light‑green
    blue_fill = PatternFill(
        fill_type="solid", start_color="BDD7EE"
    )  # light‑blue (for FAŁSZ/0)

    # ----- 2️⃣ header row -----
    for cell in ws[1]:
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")
        cell.fill = header_fill

    # ----- 3️⃣ data rows: wrap + zebra + conditional colour -----
    for row_idx, row in enumerate(ws.iter_rows(min_row=2), start=2):
        # zebra striping on even rows (2,4,6,…)
        if row_idx % 2 == 0:
            for cell in row:
                cell.fill = zebra_fill

        for cell in row:
            # ---- word‑wrap for every cell ----
            cell.alignment = wrap_align

            # ---- conditional colour based on the *displayed* value ----
            val = cell.value
            # Normalise strings (ignore case & surrounding whitespace)
            if isinstance(val, str):
                val_norm = val.strip().upper()
                if val_norm in {"1", "PRAWDA"}:
                    cell.fill = green_fill
                elif val_norm in {"0", "FAŁSZ"}:
                    cell.fill = blue_fill
            # Numeric values 0 / 1 (including Python booleans which are subclass of int)
            elif isinstance(val, (int, float)):
                if val == 1:
                    cell.fill = green_fill
                elif val == 0:
                    cell.fill = blue_fill
            # Booleans – treat True as 1, False as 0
            elif isinstance(val, bool):
                if val:
                    cell.fill = green_fill
                else:
                    cell.fill = blue_fill


def write_to_excel(
    grouped: Dict[str, List[Dict[str, Any]]], out_path: pathlib.Path
) -> None:
    """Create the workbook, write each group to a sheet and then prettify it."""
    with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
        # pandas writes the raw data first
        for sheet_name, rows in grouped.items():
            df = pd.DataFrame(rows)

            # keep ``text`` as the first column
            cols = ["text"] + [c for c in df.columns if c != "text"]
            df = df[cols]

            safe_name = sheet_name[:31]  # Excel sheet name limit
            df.to_excel(writer, sheet_name=safe_name, index=False)

        # now style the workbook with openpyxl
        workbook = writer.book
        for ws in workbook.worksheets:
            apply_pretty_formatting(ws)


def convert_jsonl_to_xlsx(jsonl_path: pathlib.Path, xlsx_path: pathlib.Path) -> None:
    """
    Convert a JSONL file to an Excel workbook.

    Args:
        jsonl_path: Path to the input JSONL file
        xlsx_path: Path where the Excel file should be saved
    """
    print(f"🔎 Loading data from {jsonl_path} …")
    raw_records = load_jsonl(jsonl_path)

    print("🔧 Flattening & grouping …")
    grouped = group_by_field(raw_records)

    print(f"🖋️ Writing workbook ({len(grouped)} sheets) …")
    write_to_excel(grouped, xlsx_path)
    print(f"✅ Excel file created → {xlsx_path.resolve()}")
